2024-06-07 23:01:55,120 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-07 23:05:03,424 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\views.py changed, reloading.
2024-06-07 23:05:14,515 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-07 23:12:10,135 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\portfolio\urls.py changed, reloading.
2024-06-07 23:12:23,751 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-07 23:15:49,852 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\urls.py changed, reloading.
2024-06-07 23:16:00,775 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-07 23:20:32,958 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-07 23:23:38,995 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-07 23:36:23,509 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\views.py changed, reloading.
2024-06-07 23:36:57,242 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-07 23:55:48,904 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\views.py changed, reloading.
2024-06-07 23:56:23,794 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-07 23:57:06,884 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\urls.py changed, reloading.
2024-06-07 23:57:37,683 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-07 23:58:15,686 - utils.exceptions - ERROR - Traceback (most recent call last):
  File "C:\Users\Ayo\Projects\portfolio_api\me\views.py", line 51, in get
    data = serializer.data
           ^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 571, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `phone` is not valid for model `ME` in `me.serializers.MESerializer`.

2024-06-07 23:58:15,719 - django.request - ERROR - Internal Server Error: /me
2024-06-07 23:58:42,709 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\serializers.py changed, reloading.
2024-06-07 23:59:02,168 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-07 23:59:19,801 - utils.exceptions - ERROR - Traceback (most recent call last):
  File "C:\Users\Ayo\Projects\portfolio_api\me\views.py", line 51, in get
    data = serializer.data
           ^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 571, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
           ^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 1079, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 1133, in get_field_names
    raise TypeError(
TypeError: The `fields` option must be a list or tuple or "__all__". Got str.

2024-06-07 23:59:19,916 - django.request - ERROR - Internal Server Error: /me
2024-06-08 00:00:48,215 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\serializers.py changed, reloading.
2024-06-08 00:01:05,879 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 00:01:20,047 - utils.exceptions - ERROR - Traceback (most recent call last):
  File "C:\Users\Ayo\Projects\portfolio_api\me\views.py", line 51, in get
    data = serializer.data
           ^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 571, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
           ^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'values'

2024-06-08 00:01:20,050 - django.request - ERROR - Internal Server Error: /me
2024-06-08 00:02:04,279 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\serializers.py changed, reloading.
2024-06-08 00:02:32,999 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 00:03:23,163 - utils.exceptions - ERROR - Traceback (most recent call last):
  File "C:\Users\Ayo\Projects\portfolio_api\me\views.py", line 51, in get
    data = serializer.data
           ^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 571, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
           ^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'values'

2024-06-08 00:03:23,175 - django.request - ERROR - Internal Server Error: /me
2024-06-08 00:06:33,829 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\views.py changed, reloading.
2024-06-08 00:06:44,626 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 00:06:59,417 - utils.exceptions - ERROR - Traceback (most recent call last):
  File "C:\Users\Ayo\Projects\portfolio_api\me\views.py", line 55, in get
    data = serializer.data
           ^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 571, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
           ^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'values'

2024-06-08 00:06:59,422 - django.request - ERROR - Internal Server Error: /me
2024-06-08 00:07:50,694 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\views.py changed, reloading.
2024-06-08 00:08:20,759 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 00:08:58,689 - utils.exceptions - ERROR - Traceback (most recent call last):
  File "C:\Users\Ayo\Projects\portfolio_api\me\views.py", line 47, in get
    data = serializer.data
           ^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
           ^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
           ^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'values'

2024-06-08 00:08:58,731 - django.request - ERROR - Internal Server Error: /me
2024-06-08 00:09:31,754 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\views.py changed, reloading.
2024-06-08 00:09:47,709 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 00:11:36,981 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\serializers.py changed, reloading.
2024-06-08 00:12:13,783 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 00:14:32,198 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 00:21:09,508 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\views.py changed, reloading.
2024-06-08 00:21:21,273 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 00:21:42,761 - django.request - ERROR - Internal Server Error: /me
Traceback (most recent call last):
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\.pyenv\pyenv-win\versions\3.11.7\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\Ayo\.pyenv\pyenv-win\versions\3.11.7\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\.pyenv\pyenv-win\versions\3.11.7\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\.pyenv\pyenv-win\versions\3.11.7\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PhoneNumber is not JSON serializable
2024-06-08 00:22:28,307 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\views.py changed, reloading.
2024-06-08 00:22:35,623 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 00:23:31,863 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\views.py changed, reloading.
2024-06-08 00:23:38,774 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 16:29:53,667 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 16:39:22,824 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 16:39:32,666 - django.request - WARNING - Not Found: /favicon.ico
2024-06-08 16:39:48,045 - django.security.csrf - WARNING - Forbidden (CSRF token from POST incorrect.): /admin/login/
2024-06-08 16:43:16,782 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 21:02:13,116 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\portfolio\urls.py changed, reloading.
2024-06-08 21:02:24,706 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 21:02:32,235 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\portfolio\urls.py changed, reloading.
2024-06-08 21:02:45,715 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 21:03:30,735 - utils.exceptions - ERROR - Traceback (most recent call last):
  File "C:\Users\Ayo\Projects\portfolio_api\experience\views.py", line 29, in list
    data: List[dict] = serializer.data
                       ^^^^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
           ^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\fields.py", line 1871, in to_representation
    method = getattr(self.parent, self.method_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ExperienceSerializer' object has no attribute 'get_self_url'

2024-06-08 21:03:30,759 - django.request - ERROR - Internal Server Error: /experiences/
2024-06-08 21:04:01,446 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\experience\serializers.py changed, reloading.
2024-06-08 21:04:07,908 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 21:04:18,695 - utils.exceptions - ERROR - Traceback (most recent call last):
  File "C:\Users\Ayo\Projects\portfolio_api\experience\views.py", line 29, in list
    data: List[dict] = serializer.data
                       ^^^^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
           ^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\fields.py", line 1872, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\experience\serializers.py", line 24, in get_self_url
    return reverse("experiences", kwargs={"pk": obj.pk}, request=request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\reverse.py", line 47, in reverse
    url = _reverse(viewname, args, kwargs, request, format, **extra)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\reverse.py", line 60, in _reverse
    url = django_reverse(viewname, args=args, kwargs=kwargs, **extra)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'experiences' not found. 'experiences' is not a valid view function or pattern name.

2024-06-08 21:04:18,982 - django.request - ERROR - Internal Server Error: /experiences/
2024-06-08 21:05:05,181 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\experience\urls.py changed, reloading.
2024-06-08 21:05:10,454 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 21:13:13,088 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\experience\serializers.py changed, reloading.
2024-06-08 21:13:27,491 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 21:17:03,338 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\experience\views.py changed, reloading.
2024-06-08 21:17:21,126 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 21:18:59,131 - django.request - WARNING - Method Not Allowed: /experiences/1/
2024-06-08 21:23:04,669 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\experience\views.py changed, reloading.
2024-06-08 21:23:13,910 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 21:24:20,586 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\experience\views.py changed, reloading.
2024-06-08 21:24:29,813 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 21:25:23,821 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 21:26:46,369 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\experience\views.py changed, reloading.
2024-06-08 21:26:55,007 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 21:27:19,974 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\experience\views.py changed, reloading.
2024-06-08 21:27:33,365 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 21:31:13,789 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\project\models.py changed, reloading.
2024-06-08 21:41:09,610 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 21:41:28,213 - django.request - WARNING - Not Found: /favicon.ico
2024-06-08 22:05:59,793 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\portfolio\urls.py changed, reloading.
2024-06-08 22:06:06,998 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 22:09:14,708 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\project\models.py changed, reloading.
2024-06-08 22:11:00,106 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 22:16:14,206 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\project\models.py changed, reloading.
2024-06-08 22:16:45,811 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 22:23:19,807 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 23:25:16,163 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\reverse.py changed, reloading.
2024-06-08 23:25:27,166 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 23:27:29,843 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\portfolio\urls.py changed, reloading.
2024-06-08 23:27:32,650 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 23:28:31,253 - utils.exceptions - ERROR - Traceback (most recent call last):
  File "C:\Users\Ayo\Projects\portfolio_api\blog\views.py", line 26, in list
    data: List[dict] = serializer.data
                       ^^^^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
           ^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\fields.py", line 1872, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\blog\serializers.py", line 16, in get_self_url
    return reverse("blog_posts_detail", kwargs={"pk": obj.pk}, request=request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\reverse.py", line 47, in reverse
    url = _reverse(viewname, args, kwargs, request, format, **extra)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\reverse.py", line 60, in _reverse
    url = django_reverse(viewname, args=args, kwargs=kwargs, **extra)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'blog_posts_detail' not found. 'blog_posts_detail' is not a valid view function or pattern name.

2024-06-08 23:28:31,260 - django.request - ERROR - Internal Server Error: /blog_posts/
2024-06-08 23:28:52,064 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\blog\serializers.py changed, reloading.
2024-06-08 23:28:54,375 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 23:30:38,488 - utils.exceptions - ERROR - Traceback (most recent call last):
  File "C:\Users\Ayo\Projects\portfolio_api\blog\views.py", line 38, in retrieve
    post: BlogPost = BlogPost.objects.get(id=kwargs["pk"])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\django\db\models\query.py", line 637, in get
    raise self.model.DoesNotExist(
blog.models.BlogPost.DoesNotExist: BlogPost matching query does not exist.

2024-06-08 23:30:38,490 - django.request - ERROR - Internal Server Error: /blog_posts/2/
2024-06-08 23:31:43,281 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\blog\views.py changed, reloading.
2024-06-08 23:31:45,728 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 23:32:08,262 - django.request - WARNING - Not Found: /blog_posts/2/
2024-06-08 23:34:01,490 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\project\views.py changed, reloading.
2024-06-08 23:34:04,626 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 23:35:12,202 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\experience\views.py changed, reloading.
2024-06-08 23:35:14,800 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-09 13:21:23,899 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-09 13:21:38,798 - django.request - WARNING - Not Found: /favicon.ico
2024-06-09 13:50:30,128 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\portfolio\urls.py changed, reloading.
2024-06-09 13:50:36,589 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-09 13:50:53,818 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\certificate\urls.py changed, reloading.
2024-06-09 13:50:58,622 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-09 15:12:38,309 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-09 16:17:44,104 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-09 16:19:41,421 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\portfolio\urls.py changed, reloading.
2024-06-09 16:19:46,491 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-09 16:20:02,950 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\portfolio\urls.py changed, reloading.
2024-06-09 16:20:09,333 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-09 16:20:17,486 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\portfolio\urls.py changed, reloading.
2024-06-09 16:20:21,720 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-09 16:20:41,010 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\portfolio\urls.py changed, reloading.
2024-06-09 16:20:46,637 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-09 16:21:42,476 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\portfolio\urls.py changed, reloading.
