2024-06-07 23:01:55,120 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-07 23:05:03,424 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\views.py changed, reloading.
2024-06-07 23:05:14,515 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-07 23:12:10,135 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\portfolio\urls.py changed, reloading.
2024-06-07 23:12:23,751 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-07 23:15:49,852 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\urls.py changed, reloading.
2024-06-07 23:16:00,775 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-07 23:20:32,958 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-07 23:23:38,995 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-07 23:36:23,509 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\views.py changed, reloading.
2024-06-07 23:36:57,242 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-07 23:55:48,904 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\views.py changed, reloading.
2024-06-07 23:56:23,794 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-07 23:57:06,884 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\urls.py changed, reloading.
2024-06-07 23:57:37,683 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-07 23:58:15,686 - utils.exceptions - ERROR - Traceback (most recent call last):
  File "C:\Users\Ayo\Projects\portfolio_api\me\views.py", line 51, in get
    data = serializer.data
           ^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 571, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `phone` is not valid for model `ME` in `me.serializers.MESerializer`.

2024-06-07 23:58:15,719 - django.request - ERROR - Internal Server Error: /me
2024-06-07 23:58:42,709 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\serializers.py changed, reloading.
2024-06-07 23:59:02,168 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-07 23:59:19,801 - utils.exceptions - ERROR - Traceback (most recent call last):
  File "C:\Users\Ayo\Projects\portfolio_api\me\views.py", line 51, in get
    data = serializer.data
           ^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 571, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
           ^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 1079, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 1133, in get_field_names
    raise TypeError(
TypeError: The `fields` option must be a list or tuple or "__all__". Got str.

2024-06-07 23:59:19,916 - django.request - ERROR - Internal Server Error: /me
2024-06-08 00:00:48,215 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\serializers.py changed, reloading.
2024-06-08 00:01:05,879 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 00:01:20,047 - utils.exceptions - ERROR - Traceback (most recent call last):
  File "C:\Users\Ayo\Projects\portfolio_api\me\views.py", line 51, in get
    data = serializer.data
           ^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 571, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
           ^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'values'

2024-06-08 00:01:20,050 - django.request - ERROR - Internal Server Error: /me
2024-06-08 00:02:04,279 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\serializers.py changed, reloading.
2024-06-08 00:02:32,999 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 00:03:23,163 - utils.exceptions - ERROR - Traceback (most recent call last):
  File "C:\Users\Ayo\Projects\portfolio_api\me\views.py", line 51, in get
    data = serializer.data
           ^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 571, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
           ^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'values'

2024-06-08 00:03:23,175 - django.request - ERROR - Internal Server Error: /me
2024-06-08 00:06:33,829 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\views.py changed, reloading.
2024-06-08 00:06:44,626 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 00:06:59,417 - utils.exceptions - ERROR - Traceback (most recent call last):
  File "C:\Users\Ayo\Projects\portfolio_api\me\views.py", line 55, in get
    data = serializer.data
           ^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 571, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
           ^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'values'

2024-06-08 00:06:59,422 - django.request - ERROR - Internal Server Error: /me
2024-06-08 00:07:50,694 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\views.py changed, reloading.
2024-06-08 00:08:20,759 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 00:08:58,689 - utils.exceptions - ERROR - Traceback (most recent call last):
  File "C:\Users\Ayo\Projects\portfolio_api\me\views.py", line 47, in get
    data = serializer.data
           ^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
           ^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
           ^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'values'

2024-06-08 00:08:58,731 - django.request - ERROR - Internal Server Error: /me
2024-06-08 00:09:31,754 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\views.py changed, reloading.
2024-06-08 00:09:47,709 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 00:11:36,981 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\serializers.py changed, reloading.
2024-06-08 00:12:13,783 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 00:14:32,198 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 00:21:09,508 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\views.py changed, reloading.
2024-06-08 00:21:21,273 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 00:21:42,761 - django.request - ERROR - Internal Server Error: /me
Traceback (most recent call last):
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\.pyenv\pyenv-win\versions\3.11.7\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\Ayo\.pyenv\pyenv-win\versions\3.11.7\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\.pyenv\pyenv-win\versions\3.11.7\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\Projects\portfolio_api\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayo\.pyenv\pyenv-win\versions\3.11.7\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PhoneNumber is not JSON serializable
2024-06-08 00:22:28,307 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\views.py changed, reloading.
2024-06-08 00:22:35,623 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-06-08 00:23:31,863 - django.utils.autoreload - INFO - C:\Users\Ayo\Projects\portfolio_api\me\views.py changed, reloading.
2024-06-08 00:23:38,774 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
